lvl1: {
    lvl2a: {
        bob.label: 'Bob'
        bob.hardware.label: 'Bob HW'
        bob.optic.label: 'Bob Optic'
        bob.optic.class: optic
        bob.daemon.class: daemon

        tom.label: 'Tom'
        tom.hardware.label: 'Tom HW'
        tom.optic.label: 'Tom Optic'
        tom.optic.class: optic

        jon.label: 'Jon'
        jon.hardware.label: 'Jon HW'
        jon.daemon.label: 'Jon Daemon'
        jon.daemon.class: daemon
    }
    lvl2b: {
        sue: "Sue Optic"
        sue->_.lvl2a.bob.optic
        sue.optic.class: optic
    }
}
