direction: right
...@../common/styles
...@../common/legend
...@../entities/zshooter_hardware.hardware_system

# Full enough for system review, but suppress overwhelming 1-Wire fanout.

**: {
  &class: entity_wrapper
  optical: suspend
  daemon: suspend
}
**: {
  &class: computer_device_node
  daemons: suspend
}

**: suspend {
  &class: onewire_temp_sensor
}
**: suspend {
  &class: cryo_temp_sensor
}
(** -> **)[*]: suspend {
  &class: sensor_fanout_conn
}

