direction: right
...@../common/styles
...@../entities/zshooter_optical.optical_system

***: suspend
(***->***)[*]: suspend


***: unsuspend {
  &class: room_container
}
***: unsuspend {
  &class: instrument_container
}
***: unsuspend {
  &class: subinstrument_container
}

***: {
  &class: entity_wrapper
  style.stroke-width: 0
  label:""
}
***: unsuspend {
    &class: optical_node
}


(***->***)[*]: unsuspend {
    &class: optical_conn
}