direction: right
...@../common/styles
software_runtime: @../entities/ics.software_runtime
drp_runtime: @../entities/drp.drp_runtime
instrument_telemetry_db: @../entities/common.instrument_telemetry_db
hardware_system: @../entities/zshooter_hardware.hardware_system
...@../models/software_commands
...@../models/software_publishes
...@../models/device_driver_links

hardware_system: {
  (**->**)[*]: suspend
  **: suspend {
    &leaf: true
  }
  **: suspend {
    &class: daemon_card_container
  }
  **: unsuspend {
    &class: req_software
  }
  **: unsuspend {
    &class: controller_device_node
  }
  **: {
    dcs_*.dewar: suspend
  }
}

# In the big runtime view, hide deeper object-model internals and engineering sections.
#***: suspend {
#  &class: object_model_container
#}
#***: suspend {
#  &class: eng_section_block
#}
#***: suspend {
#  &class: ops_section_block
#}
#***: suspend {
#  &class: event_section_block
#}
#***: suspend {
#  &class: status_section_block
#}
#***: suspend {
#  &class: config_section_block
#}
