#direction: right
...@../common/styles
...@../entities/ics.software_runtime
wmko_telemetry_db: @../entities/common.instrument_telemetry_db

...@../models/software_publishes
...@../models/device_driver_links


***: suspend
(***->***)[*]: suspend

***: unsuspend{
  &class: computer_host_container
}
***: unsuspend {
  &class: room_container
}
***: unsuspend {
  &class: instrument_container
}
***: unsuspend {
  &class: subinstrument_container
}
***: unsuspend {
  &class: ebox_enclosure_container
}

***: unsuspend {
  &class: controller_device_node
}

(***->***)[*]: unsuspend {
  &class: publish_conn
}
(***->***)[*]: unsuspend {
  &class: command_conn
}
(***->***)[*]: unsuspend {
  &class: driver_conn
}

***: {
  &class: computer_host_container
  **: unsuspend
}

***: unsuspend {
  &class: req_software
}