direction: down
...@../common/styles
...@../entities/zshooter.hardware_system

templates: suspend

(k1_rnas.zshooter.zspec.zspec_control_box.zspec_ubuntu.vis_slitcam.device.driver-> k1_rnas.zshooter.zspec.zspec_visible.slit_viewer_hw).class: driver_conn
(k1_rnas.zshooter.zspec.zspec_control_box.zspec_ubuntu.ir_slitcam.device.driver-> k1_rnas.zshooter.zspec.zspec_nir.cryostat.slit_viewer_hw).class: driver_conn
(k1_rnas.zshooter.zspec.zspec_control_box.zspec_ubuntu.zimage_filter_wheel.device.driver-> k1_rnas.zshooter.zimage.filter_wheel.hardware).class: driver_conn
(k1_rnas.zshooter.zspec.zspec_control_box.zspec_ubuntu.zimage_focus.device.driver-> k1_rnas.zshooter.zimage.focus.hardware).class: driver_conn
(k1_rnas.zshooter.zspec.zspec_control_box.zspec_ubuntu.zimage_u_rotator.device.driver-> k1_rnas.zshooter.zimage.u_rotator.hardware).class: driver_conn
(k1_rnas.zshooter.zspec.zspec_control_box.zspec_ubuntu.zimage_v_rotator.device.driver-> k1_rnas.zshooter.zimage.v_rotator.hardware).class: driver_conn
(k1_rnas.zshooter.zspec.zspec_control_box.zspec_ubuntu.zimage_z_rotator.device.driver-> k1_rnas.zshooter.zimage.z_rotator.hardware).class: driver_conn
(k1_rnas.zshooter.zspec.zspec_control_box.zspec_ubuntu.vis_rotator.device.driver-> k1_rnas.zshooter.zspec.zspec_visiblerotator.hardware).class: driver_conn
(k1_rnas.zshooter.zspec.zspec_control_box.zspec_ubuntu.vis_adc.device.driver-> k1_rnas.zshooter.zspec.zspec_visibleadc.hardware).class: driver_conn
(k1_rnas.zshooter.zspec.zspec_control_box.zspec_ubuntu.vis_nodder.device.driver-> k1_rnas.zshooter.zspec.zspec_visiblenod.hardware).class: driver_conn
(k1_rnas.zshooter.zspec.zspec_control_box.zspec_ubuntu.vis_slit.device.driver-> k1_rnas.zshooter.zspec.zspec_visibleslit.hardware).class: driver_conn
(k1_rnas.zshooter.zspec.zspec_control_box.zspec_ubuntu.zspec_focus_b.device.driver-> k1_rnas.zshooter.zspec.zspec_visible.dcs_b.focus.hardware).class: driver_conn
(k1_rnas.zshooter.zspec.zspec_control_box.zspec_ubuntu.zspec_focus_g.device.driver-> k1_rnas.zshooter.zspec.zspec_visible.dcs_g.focus.hardware).class: driver_conn
(k1_rnas.zshooter.zspec.zspec_control_box.zspec_ubuntu.zspec_focus_r.device.driver-> k1_rnas.zshooter.zspec.zspec_visible.dcs_r.focus.hardware).class: driver_conn
(k1_rnas.zshooter.zspec.zspec_control_box.zspec_ubuntu.ir_rotator.device.driver-> k1_rnas.zshooter.zspec.zspec_nir.cryostat.rotator.hardware).class: driver_conn
(k1_rnas.zshooter.zspec.zspec_control_box.zspec_ubuntu.ir_adc.device.driver-> k1_rnas.zshooter.zspec.zspec_nir.cryostat.adc.hardware).class: driver_conn
(k1_rnas.zshooter.zspec.zspec_control_box.zspec_ubuntu.ir_nodder.device.driver-> k1_rnas.zshooter.zspec.zspec_nir.cryostat.nodder.hardware).class: driver_conn
(k1_rnas.zshooter.zspec.zspec_control_box.zspec_ubuntu.ir_slit.device.driver-> k1_rnas.zshooter.zspec.zspec_nir.cryostat.slit.hardware).class: driver_conn
(k1_rnas.zshooter.zspec.zspec_control_box.zspec_ubuntu.zfront_control.device.sel_driver-> k1_rnas.zshooter.zfront.selector_controller).class: driver_conn
(k1_rnas.zshooter.zspec.zspec_control_box.zspec_ubuntu.zfront_control.device.cal_driver-> k1_rnas.zshooter.zfront.zcal.cal_controller).class: driver_conn
(k1_rnas.zshooter.zspec.zspec_control_box.zspec_ubuntu.glycol_monitor.device.driver-> k1_rnas.zshooter.glycol_manifold).class: driver_conn
(k1_rnas.zshooter.zspec.zspec_control_box.zspec_ubuntu.temp_log.device.driver-> k1_rnas.zshooter.zspec.zspec_visible.temp_monitor_hub_hw).class: driver_conn
(k1_rnas.zshooter.zspec.zspec_control_box.zspec_ubuntu.temp_log.device.driver-> k1_rnas.zshooter.zimage.temp_monitor_hub_hw).class: driver_conn
(k1_rnas.zshooter.zspec.zspec_control_box.zspec_ubuntu.temp_log.device.ir_driver-> k1_rnas.zshooter.zspec.zspec_nir.temp_controller_hw).class: driver_conn
(k1_rnas.zshooter.zspec.zspec_control_box.zspec_ubuntu.vacuum_monitor-> k1_rnas.zshooter.zspec.zspec_visible.dcs_*.vacuum_gauge).class: driver_conn
(k1_rnas.zshooter.zspec.zspec_control_box.zspec_ubuntu.vacuum_monitor-> k1_rnas.zshooter.zspec.zspec_nir.vacuum_gauge).class: driver_conn
(k1_rnas.zshooter.zspec.zspec_control_box.zspec_ubuntu.shutter_monitor-> k1_rnas.zshooter.zspec.zspec_nir.cryostat.shutter.hardware).class: driver_conn
(k1_rnas.zshooter.zspec.zspec_control_box.zspec_ubuntu.shutter_monitor-> k1_rnas.zshooter.zspec.zspec_visible.shutter.hardware).class: driver_conn

k1_server_room.zimage_readout_computer: {
  notebook_server: @../entities/common.jupyter_notebook_server
  readout_u: @devices.orca_readout.daemon
  readout_u.label: 'u Readout'
  readout_v: @devices.orca_readout.daemon
  readout_v.label: 'v Readout'
  readout_z: @devices.orca_readout.daemon
  readout_z.label: 'z Readout'
}

k1_server_room.zspec_readout_computer: {
  notebook_server: @../entities/common.jupyter_notebook_server
  readout_opt_b: @zspec.zspec.zspec_visible.dcs_b.readout.daemon
  readout_opt_g: @zspec.zspec.zspec_visible.dcs_g.readout.daemon
  readout_opt_r: @zspec.zspec.zspec_visible.dcs_r.readout.daemon
  readout_ir_yj: @zspec.zspec.zspec_nir.readout_yj.daemon
  readout_ir_h: @zspec.zspec.zspec_nir.readout_h.daemon
  readout_ir_k: @zspec.zspec.zspec_nir.readout_k.daemon
  readout_opt_b.label: "Archon B (qCCDDaemon)"
  readout_opt_g.label: "Archon G (qCCDDaemon)"
  readout_opt_r.label: "Archon R (qCCDDaemon)"
  readout_ir_yj.label: "Archon YJ (APDDaemon)"
  readout_ir_h.label: "Archon H (APDDaemon)"
  readout_ir_k.label: "Archon K (APDDaemon)"
}

k1_rnas.zshooter.zspec.zspec_control_box.zspec_ubuntu: {
    zfront_control: @daemons.zfront_control
    spec_focus: @daemons.focus_controller
    spec_focus.label: ZSpec Focus Controller
    image_focus: @daemons.focus_controller
    image_focus.label: ZImage Focus Controller
    vacuum_monitor: @daemons.vacuum_monitor
    fine_guiding: @daemons.fine_guiding

    vis_slitcam: @zspec.zspec.zspec_visible.slit_viewer.daemon
    ir_slitcam: @zspec.zspec.zspec_nir.cryostat.slit_viewer.daemon
    zimage_filter_wheel: @zimage.zimage.filter_wheel.daemon
    zimage_focus: @zimage.zimage.focus.daemon
    zimage_u_rotator: @zimage.zimage.u_rotator.daemon
    zimage_v_rotator: @zimage.zimage.v_rotator.daemon
    zimage_z_rotator: @zimage.zimage.z_rotator.daemon
    zimage_u_rotator.label: "u Rotator (`ZIRotatorDaemon`)"
    zimage_v_rotator.label: "v Rotator (`ZIRotatorDaemon`)"
    zimage_z_rotator.label: "z Rotator (`ZIRotatorDaemon`)"
    vis_rotator: @zspec.zspec.zspec_visiblerotator.daemon
    vis_adc: @zspec.zspec.zspec_visibleadc.daemon
    vis_nodder: @zspec.zspec.zspec_visiblenod.daemon
    vis_slit: @zspec.zspec.zspec_visibleslit.daemon
    zspec_focus_b: @zspec.zspec.zspec_visible.dcs_b.focus.daemon
    zspec_focus_g: @zspec.zspec.zspec_visible.dcs_g.focus.daemon
    zspec_focus_r: @zspec.zspec.zspec_visible.dcs_r.focus.daemon
    zspec_focus_ir: "Run @ Cooldown"
    ir_rotator: @zspec.zspec.zspec_nir.cryostat.rotator.daemon
    ir_adc: @zspec.zspec.zspec_nir.cryostat.adc.daemon
    ir_nodder: @zspec.zspec.zspec_nir.cryostat.nodder.daemon
    ir_slit: @zspec.zspec.zspec_nir.cryostat.slit.daemon
    shutter_monitor
    glycol_monitor
    temp_log

    fine_guiding -> ir_nodder: {
      class: command_conn
      label: command
    }
    fine_guiding -> ir_rotator: {
      class: command_conn
      label: command
    }
    fine_guiding -> ir_adc: {
      class: command_conn
      label: command
    }
    fine_guiding -> vis_nodder: {
      class: command_conn
      label: command
    }
    fine_guiding -> vis_rotator: {
      class: command_conn
      label: command
    }
    fine_guiding -> vis_adc: {
      class: command_conn
      label: command
    }
    image_focus -> zimage_focus: {
      class: command_conn
      label: command
    }
    spec_focus -> zspec_focus_*: {
      class: command_conn
      label: command
    }
  }

(**->**)[*]: suspend
**: suspend {
  &leaf: true
}
#**: unsuspend {
#  &class: daemon_card_container
#}
**: unsuspend {
  &class: req_software
}
**: unsuspend {
  &class: controller_device_node
}
**: {
  dcs_*.dewar: suspend
}



# In the big runtime view, hide deeper object-model internals and engineering sections.
***: suspend {
  &class: object_model_container
}
***: suspend {
  &class: eng_section_block
}
***: suspend {
  &class: ops_section_block
}
***: suspend {
  &class: event_section_block
}
***: suspend {
  &class: status_section_block
}
***: suspend {
  &class: config_section_block
}
