drp_runtime: {
  class: instrument_container
  label: DRP Runtime
  drp_pc: {
    class: computer_host_container
    label: DRP PC
    raw_archive_writer: {
      class: daemon_card_container
      label: Raw Archive Writer
      config: {
        class: config_section_block
        label: config
        "main.yaml": drp.raw_archive
        "logger.yaml": present
      }
      status: {
        class: status_section_block
        label: status
        "archive_state": State
      }
      events: {
        class: event_section_block
        label: events
        "archive_write_complete": Event
      }
      ops: {
        class: ops_section_block
        label: ops
        "subscribe_raw_stream(...)"
        "write_raw_package(...)"
      }
    }
    prelim_reducer: {
      class: daemon_card_container
      label: Preliminary Reducer
      config: {
        class: config_section_block
        label: config
        "main.yaml": drp.prelim
        "logger.yaml": present
      }
      status: {
        class: status_section_block
        label: status
        "reduce_state": State
      }
      events: {
        class: event_section_block
        label: events
        "prelim_products_ready": Event
      }
      ops: {
        class: ops_section_block
        label: ops
        "subscribe_raw_stream(...)"
        "emit_prelim_products(...)"
      }
    }
  }
}
