facility_air: {
  class: [utility_node; air_utility]
  label: Facility Air
}

facility_glycol: {
  class: [utility_node; glycol_utility]
  label: Facility Glycol
}

facility_ac: {
  class: [utility_node; ac_utility]
  label: Facility AC
}

facility_1000base_t: {
  class: [utility_node; ethernet_utility]
  label: Facility 1000BASE-T
}

facility_ethernet: {
  class: [utility_node; ethernet_utility]
  label: Facility Ethernet
}

facility_10plusbase_t: {
  class: [utility_node; ethernet_utility]
  label: Facility 10+BASE-T
}

observatory_archive: {
  class: [service_node; archive_service]
  label: Observatory Archive
}

keck_telescope: {
  class: [utility_node; telescope_source]
  label: Telescope Beam
}

left_instrument: {
  class: neighbor_instrument
  label: Left Instrument
}

right_instrument: {
  class: neighbor_instrument
  label: Right Instrument
}
