
temp_monitor_module: {
    temp_monitor_hub_hw: @common.onewire_hub_block
    temp_monitor_hub_hw.label: 1-Wire Temp Monitor
    temp_monitor_hub_sw: @daemons.temp_monitor

    temp_sensor_1: @common.onewire_temp_sensor_block
    temp_sensor_1.label: Temp Sensor 1
    temp_sensor_2: @common.onewire_temp_sensor_block
    temp_sensor_2.label: Temp Sensor ...
    temp_sensor_3: @common.onewire_temp_sensor_block
    temp_sensor_3.label: Temp Sensor N
    
    (temp_monitor_hub_hw->temp_sensor_*).class: sensor_fanout_conn
}


dcs: {
    class: entity_wrapper
    label: Detector System

    focus_hw: @devices.focus.hardware
    focus_sw: @devices.focus.daemon

    readout_hw: @devices.archon_readout.hardware
    readout_sw: @devices.archon_readout.daemon

    vacuum_gauge: @common.vacuum_gauge
    cryocooler: @common.cryocooler

    dewar: {
        class: cryostat_container
        vib: @common.vib
        detector: {
          class: detector_device_node
          label: qCCD w/heater & temp
        }
        (vib -> detector).class: detector_conn
    }
    (readout_hw -> dewar.vib).class: detector_conn

}