zfront: {
  hardware: {
    class: subinstrument_container
    label: ZFront
    zfront_dc_distribution: @common.ac_to_dc_block
    zfront_data_hub: @common.network_switch_block

    zfront_instrument_selector: {
      class: [motion_device_node; serial_device]
      label: Instrument Selector
    }
    zfront_zim_zcal_selector: {
      class: [motion_device_node; serial_device]
      label: "ZSpec / ZImage Selector"
    }
    zfront_embedded_controller: {
      class: [controller_device_node; ethernet_device]
      label: ZFront Embedded Controller
    }
    (zfront_dc_distribution->zfront_data_hub).class: dc_conn
    (zfront_dc_distribution->zcal.zcal_embedded_controller).class: dc_conn
    (zfront_dc_distribution->zfront_embedded_controller).class: dc_conn
    (zfront_embedded_controller->zfront_instrument_selector).class: motor_control_conn
    (zfront_embedded_controller->zfront_zim_zcal_selector).class: motor_control_conn

    (zfront_data_hub->zfront_embedded_controller).class: network_conn
    (zfront_data_hub->zcal.zcal_embedded_controller).class: network_conn

    zcal: {
      class: subinstrument_container
      label: ZCal
      zcal_cathode_lamps: {
        class: [device_node]
        label: Cathode Lamps
      }
      zcal_led_lamps: {
        class: [device_node]
        label: LED Lamps
      }
      zcal_quartz_lamps: {
        class: [device_node]
        label: Quartz Lamps
      }
      zcal_embedded_controller: {
        class: [controller_device_node; ethernet_device]
        label: ZCal Embedded Controller
      }
      zcal_high_voltage_supply: {
        class: [device_node]
        label: High Voltage Supply
      }
      (zcal_embedded_controller -> zcal_quartz_lamps).class: custom_conn
      (zcal_embedded_controller -> zcal_led_lamps).class: custom_conn
      (zcal_embedded_controller -> zcal_high_voltage_supply).class: custom_conn
      (zcal_high_voltage_supply -> zcal_cathode_lamps).class: dc_conn
      (zcal_high_voltage_supply -> zcal_cathode_lamps)[*].label: "HV DC"

    }
  }
}