zimage: {
  class: subinstrument_container
  label: ZImage
  ebox: {
    class: ebox_enclosure_container
    label: ZImage EBox
    ac_distribution: @common.ac_distribution_block
    dc_bus: @common.ac_to_dc_block

    data_hub: @common.data_hub_block
    motor_control_hw: @devices.motor_controller.hardware
    motor_control_sw: @devices.motor_controller.daemon

    ubuntu: {
      class: [computer_device_node; ethernet_device; optional_node]
      label: ZImage Ubuntu
    }
    (ac_distribution->dc_bus).class: ac_conn
    (ac_distribution->ubuntu).class: [ac_conn; optional_conn]

    (dc_bus->data_hub).class: dc_conn
    (dc_bus->motor_control_hw).class: dc_conn

    (ubuntu->data_hub).class: [data_conn; optional_conn]
    (data_hub->motor_control_hw).class: data_conn
  }

  glycol_submanifold: @common.glycol_manifold_block

  ...@subsystems.temp_monitor_module

  filter_wheel_hw: @devices.filter_wheel.hardware
  filter_wheel_sw: @devices.filter_wheel.daemon
  filter_wheel_op: @devices.filter_wheel.optical
  focus_hw: @devices.focus.hardware
  focus_sw: @devices.focus.daemon

  u_rotator_hw: @devices.opt_rotator.hardware
  u_rotator_hw.label: u Detector Rotator
  u_rotator_sw: @devices.opt_rotator.daemon
  u_rotator_sw.label: u Detector Rotator

  v_rotator_hw: @devices.opt_rotator.hardware
  v_rotator_hw.label: v Detector Rotator
  v_rotator_sw: @devices.opt_rotator.daemon
  v_rotator_sw.label: v Detector Rotator

  z_rotator_hw: @devices.opt_rotator.hardware
  z_rotator_hw.label: z Detector Rotator
  z_rotator_sw: @devices.opt_rotator.daemon
  z_rotator_sw.label: z Detector Rotator

  u_detector: @common.quest2_detector
  v_detector: @common.quest2_detector
  z_detector: @common.quest2_detector
  u_detector.label: 'u Orca-Quest2'
  v_detector.label: 'v Orca-Quest2'
  z_detector.label: 'z Orca-Quest2'

  (ebox.data_hub->glycol_submanifold).class: data_conn
  (ebox.data_hub->temp_monitor_hub_hw).class: data_conn

  (ebox.motor_control_hw->filter_wheel_hw).class: motor_control_conn
  (ebox.motor_control_hw->focus_hw).class: motor_control_conn
  (ebox.motor_control_hw->u_rotator_hw).class: motor_control_conn
  (ebox.motor_control_hw->v_rotator_hw).class: motor_control_conn
  (ebox.motor_control_hw->z_rotator_hw).class: motor_control_conn

  (ebox.data_hub->u_detector).class: data_conn
  (ebox.data_hub->v_detector).class: data_conn
  (ebox.data_hub->z_detector).class: data_conn

  (glycol_submanifold->u_detector).class: glycol_conn
  (glycol_submanifold->v_detector).class: glycol_conn
  (glycol_submanifold->z_detector).class: glycol_conn
}
