optical_system: {
  label: Optical Train

  tel: @external.keck_telescope
  inst_sel: @zfront.zfront.inst_selector
  left_inst: @external.left_instrument
  right_inst: @external.right_instrument

  zfront: @zfront.zfront

  zs: {
    class: instrument_container
    label: ZShooter

      zspec_visible: @zspec.zspec.zspec_visible
      cryostat: @zspec.zspec.zspec_nir.cryostat

      zss_dichroic: {
        class: optical_node
        label: ZSpec Dichroic
      }
      zspec_visible.coll_echelle_xdisp: {
        class: optical_node
        label: Visible Spectrograph
      }
      zspec_visible.camera_b: {
        class: optical_node
        label: Visible Camera B
      }
      zspec_visible.camera_g: {
        class: optical_node
        label: Visible Camera G
      }
      zspec_visible.camera_r: {
        class: optical_node
        label: Visible Camera R
      }

      (zspec_visible.slit_op -> zspec_visible.coll_echelle_xdisp -> zspec_visible.camera_*).class: optical_conn
      (zspec_visible.camera_b -> zspec_visible.dcs_b.dewar.detector).class: optical_conn
      (zspec_visible.camera_g -> zspec_visible.dcs_g.dewar.detector).class: optical_conn
      (zspec_visible.camera_r -> zspec_visible.dcs_r.dewar.detector).class: optical_conn

      cryostat.coll_echelle_xdisp: {
        class: optical_node
        label: nIR Spectrograph
      }
      cryostat.camera_yj: {
        class: optical_node
        label: nIR Camera YJ
      }
      cryostat.camera_h: {
        class: optical_node
        label: nIR Camera H
      }
      cryostat.camera_k: {
        class: optical_node
        label: nIR Camera K
      }
      (cryostat.slit_op -> cryostat.coll_echelle_xdisp -> cryostat.camera_*).class: optical_conn
      (cryostat.camera_yj -> cryostat.apd_yj).class: optical_conn
      (cryostat.camera_h -> cryostat.apd_h).class: optical_conn
      (cryostat.camera_k -> cryostat.apd_k).class: optical_conn

      (zss_dichroic -> zspec_visible.shutter_op).class: optical_conn
      (zss_dichroic -> cryostat.shutter_op).class: optical_conn


      zimage: @zimage.zimage

      zimage.zsi_dichroic_u: {
        class: optical_node
        label: ZImage u Longpass
      }
      zimage.zsi_dichroic_z: {
        class: optical_node
        label: ZImage z Longpass
      }

      zimage.zsi_z_fold: {
        class: optical_node
        label: ZImage z Fold
      }

      zimage.zsi_u_cam: {
        class: optical_node
        label: u Camera
      }
      zimage.zsi_v_cam: {
        class: optical_node
        label: v Camera
      }
      zimage.zsi_z_cam: {
        class: optical_node
        label: z Camera
      }

      (zimage.zsi_dichroic_u -> zimage.zsi_u_cam -> zimage.u_detector).class: optical_conn
      (zimage.zsi_dichroic_u -> zimage.zsi_dichroic_z -> zimage.filter_wheel_op -> zimage.zsi_v_cam).class: optical_conn

      (zimage.zsi_v_cam-> zimage.v_detector).class: optical_conn
      (zimage.zsi_dichroic_z->zimage.zsi_z_fold->zimage.zsi_z_cam-> zimage.z_detector).class: optical_conn

  }

  (tel -> zfront.inst_selector).class: optical_conn
  (zfront.zim_zspec_selector -> zs.zss_dichroic).class: optical_conn
  (zfront.zim_zspec_selector -> zs.zimage.zsi_dichroic_u).class: optical_conn

  zfront.inst_selector -> left_inst: {
    class: optical_conn
    label: to Left
  }
  
  zfront.inst_selector -> right_inst: {
    class: optical_conn
    label: to Right
  }
}