zspec: {
  class: subinstrument_container
  zspec_visible: {
    class: subinstrument_container
    label: ZSpec Visible

    motor_controller_hw: @devices.motor_controller.hardware
    motor_controller_sw: @devices.motor_controller.daemon

    data_hub: @common.data_hub_block
    data_hub.label: "Optical Data Hub (Eth/USB)"

    dc_distribution: @common.dc_distribution_block
    dc_distribution.label: Optical DC Distribution

    slit_viewer_hw: @devices.slit_viewer.hardware
    slit_viewer_sw: @devices.slit_viewer.daemon
    slit_viewer_hw.label: Visible Slit Viewer
    slit_viewer_sw.label: "Visible Slit Camera Daemon"

    ...@subsystems.temp_monitor_module

    shutter_hw: {
        class: [motion_device_node; controller_device_node]
        label: Light Shutter
    }
    shutter_op: Shutter
    shutter_op.class: optical_node

    rotator_hw: @devices.opt_rotator.hardware
    adc_hw: @devices.opt_adc.hardware
    nodder_hw: @devices.opt_nodder.hardware
    slit_hw: @devices.opt_slit.hardware
    rotator_sw: @devices.opt_rotator.daemon
    adc_sw: @devices.opt_adc.daemon
    nodder_sw: @devices.opt_nodder.daemon
    slit_sw: @devices.opt_slit.daemon
    rotator_op: @devices.opt_rotator.optical
    adc_op: @devices.opt_adc.optical
    nodder_op: @devices.opt_nodder.optical
    slit_op: @devices.opt_slit.optical

    (shutter_op -> rotator_op -> adc_op -> nodder_op -> slit_op -> slit_viewer_hw).class: optical_conn

    dcs_b: @subsystems.dcs
    dcs_b.focus_hw.label: Focus B
    dcs_b.focus_sw.label: Focus B
    dcs_b.readout_hw.label: Readout B
    dcs_b.readout_sw.label: Readout B
    dcs_b.vacuum_gauge.label: Vacuum Gauge B
    dcs_b.cryocooler.label: Cryocooler B
    dcs_b.dewar.detector.label: qCCD B w/heater & temp

    dcs_g: @subsystems.dcs
    dcs_g.focus_hw.label: Focus G
    dcs_g.focus_sw.label: Focus G
    dcs_g.readout_hw.label: Readout G
    dcs_g.readout_sw.label: Readout G
    dcs_g.vacuum_gauge.label: Vacuum Gauge G
    dcs_g.cryocooler.label: Cryocooler G
    dcs_g.dewar.detector.label: qCCD G w/heater & temp

    dcs_r: @subsystems.dcs
    dcs_r.focus_hw.label: Focus R
    dcs_r.focus_sw.label: Focus R
    dcs_r.readout_hw.label: Readout R
    dcs_r.readout_sw.label: Readout R
    dcs_r.vacuum_gauge.label: Vacuum Gauge R
    dcs_r.cryocooler.label: Cryocooler R
    dcs_r.dewar.detector.label: qCCD R w/heater & temp

    (motor_controller_hw -> rotator_hw).class: motor_control_conn
    (motor_controller_hw -> adc_hw).class: motor_control_conn
    (motor_controller_hw -> nodder_hw).class: motor_control_conn
    (motor_controller_hw -> slit_hw).class: motor_control_conn
    (motor_controller_hw -> dcs_*.focus_hw).class: motor_control_conn

    (dcs_*.readout_hw->shutter_hw).class: data_conn
    (shutter_hw->data_hub).class: data_conn

    (dc_distribution -> shutter_hw).class: dc_conn
    (dc_distribution -> slit_viewer_hw).class: dc_conn
    (dc_distribution -> data_hub).class: dc_conn
    (dc_distribution -> motor_controller_hw).class: dc_conn
    (dc_distribution -> dcs_*.cryocooler).class: dc_conn
    (dc_distribution -> dcs_*.vacuum_gauge).class: dc_conn

    (data_hub -> slit_viewer_hw).class: network_conn

    (data_hub -> temp_monitor_hub_hw).class: data_conn
    (data_hub -> dcs_*.cryocooler).class: data_conn
    (data_hub -> dcs_*.vacuum_gauge).class: data_conn
    (data_hub -> motor_controller_hw).class: data_conn
  }


  zspec_nir: {
    class: subinstrument_container
    label: ZSpec nIR

    motor_controller_hw: @devices.motor_controller.hardware
    motor_controller_sw: @devices.motor_controller.daemon

    temp_controller_hw: {
      class: [controller_device_node; ethernet_device]
      label: nIR Temp Controller
    }

    coldhead: {
      class: device_node
      label: Coldhead
    }
    vacuum_gauge: @common.vacuum_gauge
    vacuum_gauge.label: Vacuum Gauge nIR

    data_hub: @common.data_hub_block
    data_hub.label: "nIR Data Hub (Eth/USB)"

    dc_distribution: @common.dc_distribution_block
    dc_distribution.label: nIR DC Distribution

    readout_yj_hw: @devices.archon_readout.hardware
    readout_yj_sw: @devices.archon_readout.daemon
    readout_yj_hw.label: YJ Archon
    readout_yj_sw.label: YJ Archon
    readout_h_hw: @devices.archon_readout.hardware
    readout_h_sw: @devices.archon_readout.daemon
    readout_h_hw.label: H Archon
    readout_h_sw.label: H Archon
    readout_k_hw: @devices.archon_readout.hardware
    readout_k_sw: @devices.archon_readout.daemon
    readout_k_hw.label: K Archon
    readout_k_sw.label: K Archon

    (readout_*_hw->cryostat.detector_vib).class: detector_con
    (data_hub->cryostat.support_vib).class: data_conn
    (data_hub->temp_controller_hw).class: data_conn
    (data_hub->vacuum_gauge).class: data_conn
    (dc_distribution->vacuum_gauge).class: dc_conn
    (dc_distribution->data_hub).class: dc_conn
    (dc_distribution->motor_controller_hw).class: dc_conn
    (dc_distribution->temp_controller_hw).class: dc_conn
    (data_hub->motor_controller_hw).class: data_conn
    (temp_controller_hw->cryostat.support_vib).class: custom_conn
    (motor_controller_hw->cryostat.support_vib).class: motor_control_conn
    shutter_sw: Shutter
    shutter_sw.class: optical_node

    cryostat: {
      class: cryostat_container
      label: nIR Cryostat

      support_vib: @common.vib
      support_vib.label: Support & Motion VIB
      detector_vib: @common.vib
      detector_vib.label: Detector VIB

      shutter_hw: {
          class: [motion_device_node; controller_device_node]
          label: Cryo Light Shutter
      }
      shutter_op: Shutter
      shutter_op.class: optical_node

      rotator_hw: @devices.ir_rotator.hardware
      rotator_op: @devices.ir_rotator.optical
      rotator_sw: @devices.ir_rotator.daemon
      adc_hw: @devices.ir_adc.hardware
      adc_op: @devices.ir_adc.optical
      adc_sw: @devices.ir_adc.daemon
      nodder_hw: @devices.ir_nodder.hardware
      nodder_op: @devices.ir_nodder.optical
      nodder_sw: @devices.ir_nodder.daemon
      slit_hw: @devices.ir_slit.hardware
      slit_op: @devices.ir_slit.optical
      slit_sw: @devices.ir_slit.daemon
      slit_viewer_hw: @devices.slit_viewer.hardware
      slit_viewer_sw: @devices.slit_viewer.daemon
      slit_viewer_hw.class: [camera_device_node; req_software]
      slit_viewer_hw.label: nIR Slit Viewer
      slit_viewer_sw.label: "IR Slit Camera Daemon"

      (shutter_op -> rotator_op -> adc_op -> nodder_op -> slit_op -> slit_viewer_hw).class: optical_conn

      focus_yj_hw: @devices.cryofocus.hardware
      focus_yj_sw: @devices.cryofocus.daemon
      focus_yj_hw.label: Focus YJ
      focus_yj_sw.label: Focus YJ
      focus_h_hw: @devices.cryofocus.hardware
      focus_h_sw: @devices.cryofocus.daemon
      focus_h_hw.label: Focus H
      focus_h_sw.label: Focus H
      focus_k_hw: @devices.cryofocus.hardware
      focus_k_sw: @devices.cryofocus.daemon
      focus_k_hw.label: Focus K
      focus_k_sw.label: Focus K

      (support_vib -> shutter_hw).class: motor_control_conn
      (support_vib -> rotator_hw).class: motor_control_conn
      (support_vib -> adc_hw).class: motor_control_conn
      (support_vib -> nodder_hw).class: motor_control_conn
      (support_vib -> slit_hw).class: motor_control_conn
      (support_vib -> focus*_hw).class: motor_control_conn
      (support_vib -> slit_viewer_hw).class: detector_conn

      heaters: {
        class: device_node
        label: Heaters
      }
      (support_vib->heaters).class: dc_conn
      (support_vib->heaters)[*].label: "DC (High Current)"

      temp_sensor_1: {
        class: [sensor_device_node; cryo_temp_sensor]
        label: Cryo Temp Sensor 1
      }
      temp_sensor_2: {
        class: [sensor_device_node; cryo_temp_sensor]
        label: Cryo Temp Sensor ...
      }
      temp_sensor_3: {
        class: [sensor_device_node; cryo_temp_sensor]
        label: Cryo Temp Sensor N
      }
      (support_vib-> temp_sensor_*).class: sensor_fanout_conn

      apd_yj: @common.apd_detector
      apd_h: @common.apd_detector
      apd_k: @common.apd_detector

      apd_yj.label: "YJ 2k sq APD w/heater & temp"
      apd_h.label: "H 2k sq APD w/heater & temp"
      apd_k.label: "K 2k sq APD w/heater & temp"

      detector_vib -> apd_* :{
        class: detector_conn
      }

    }


  }

  zspec_control_box: {
    class: ebox_enclosure_container
    label: ZSpec Control Box

    zspec_ac_distribution: @common.ac_distribution_block
    zspec_dc_bus: @common.ac_to_dc_block
    zspec_network_switch: @common.network_switch_block
    zspec_data_hub: @common.data_hub_block
    zspec_ubuntu: {
      class: [computer_device_node; ethernet_device]
      label: ZSpec Ubuntu
    }
    zspec_heat_exchanger: {
      class: device_node
      label: Heat Exchanger
    }
    zspec_supporting_electronics: {
      class: device_node
      label: Supporting Electronics
    }

    zspec_ac_distribution -> zspec_dc_bus
    zspec_ac_distribution -> zspec_ubuntu

    zspec_dc_bus -> zspec_data_hub
    zspec_dc_bus -> zspec_supporting_electronics
    zspec_dc_bus -> zspec_network_switch
    #zspec_ac_distribution -> zspec_network_switch

    (zspec_ac_distribution -> *)[*] : {
      class: ac_conn
    }
    (zspec_dc_bus -> *)[*] : {
      class: dc_conn
    }
    zspec_ubuntu <- zspec_network_switch -> zspec_supporting_electronics: {
      class: network_conn
    }
    zspec_ubuntu -> zspec_data_hub -> zspec_supporting_electronics: {
      class: data_conn
    }
  }
  (zspec_control_box.zspec_network_switch -> zspec_nir.readout*_hw).class: network_conn
  (zspec_control_box.zspec_network_switch -> zspec_visible.dcs_*.readout_hw).class: network_conn
  (zspec_control_box.zspec_ac_distribution -> zspec_nir.readout*_hw).class: ac_conn
  (zspec_control_box.zspec_ac_distribution -> zspec_visible.dcs_*.readout_hw).class: ac_conn
  (zspec_control_box.zspec_dc_bus -> zspec_visible.dc_distribution).class: dc_conn
  (zspec_control_box.zspec_dc_bus -> zspec_nir.dc_distribution).class: dc_conn

  (zspec_control_box.zspec_data_hub -> zspec_nir.data_hub).class: data_conn
  (zspec_control_box.zspec_data_hub -> zspec_visible.data_hub).class: data_conn
}