direction: down
...@../../common/styles
hardware_system: @../../entities/zshooter.hardware_system
...@../../models/hardware_connections

# Remove ZSpec from the canonical hardware system.
hardware_system.k1_rnas.zshooter.zspec: {
  suspend: true
}
