zimage_readout_pc.readout_u -> zshooter_sys.k1_rnas.zshooter.zimage.u_detector: {
  class: coaxpress_conn
  label: driver
}
zimage_readout_pc.readout_v -> zshooter_sys.k1_rnas.zshooter.zimage.v_detector: {
  class: coaxpress_conn
  label: driver
}
zimage_readout_pc.readout_z -> zshooter_sys.k1_rnas.zshooter.zimage.z_detector: {
  class: coaxpress_conn
  label: driver
}
zspec_readout_pc.readout_opt_b -> zshooter_sys.k1_rnas.zshooter.zspec.zspec_visible.dcs_b.readout_hw: {
  class: detector_conn
  label: driver
}
zspec_readout_pc.readout_opt_g -> zshooter_sys.k1_rnas.zshooter.zspec.zspec_visible.dcs_g.readout_hw: {
  class: detector_conn
  label: driver
}
zspec_readout_pc.readout_opt_r -> zshooter_sys.k1_rnas.zshooter.zspec.zspec_visible.dcs_r.readout_hw: {
  class: detector_conn
  label: driver
}
zspec_readout_pc.readout_ir_yj -> zshooter_sys.k1_rnas.zshooter.zspec.zspec_nir.readout_yj_hw: {
  class: detector_conn
  label: driver
}
zspec_readout_pc.readout_ir_h -> zshooter_sys.k1_rnas.zshooter.zspec.zspec_nir.readout_h_hw: {
  class: detector_conn
  label: driver
}
zspec_readout_pc.readout_ir_k -> zshooter_sys.k1_rnas.zshooter.zspec.zspec_nir.readout_k_hw: {
  class: detector_conn
  label: driver
}

(zshooter_sys.k1_rnas.zshooter.zspec.zspec_control_box.zspec_ubuntu.vis_slitcam->zshooter_sys.k1_rnas.zshooter.zspec.zspec_visible.slit_viewer_hw).class: driver_conn
(zshooter_sys.k1_rnas.zshooter.zspec.zspec_control_box.zspec_ubuntu.ir_slitcam->zshooter_sys.k1_rnas.zshooter.zspec.zspec_nir.cryostat.slit_viewer_hw).class: driver_conn
(zshooter_sys.k1_rnas.zshooter.zspec.zspec_control_box.zspec_ubuntu.zimage_filter_wheel->zshooter_sys.k1_rnas.zshooter.zimage.filter_wheel_hw).class: driver_conn
(zshooter_sys.k1_rnas.zshooter.zspec.zspec_control_box.zspec_ubuntu.zimage_focus->zshooter_sys.k1_rnas.zshooter.zimage.focus_hw).class: driver_conn
(zshooter_sys.k1_rnas.zshooter.zspec.zspec_control_box.zspec_ubuntu.zimage_u_rotator->zshooter_sys.k1_rnas.zshooter.zimage.u_rotator_hw).class: driver_conn
(zshooter_sys.k1_rnas.zshooter.zspec.zspec_control_box.zspec_ubuntu.zimage_v_rotator->zshooter_sys.k1_rnas.zshooter.zimage.v_rotator_hw).class: driver_conn
(zshooter_sys.k1_rnas.zshooter.zspec.zspec_control_box.zspec_ubuntu.zimage_z_rotator->zshooter_sys.k1_rnas.zshooter.zimage.z_rotator_hw).class: driver_conn
(zshooter_sys.k1_rnas.zshooter.zspec.zspec_control_box.zspec_ubuntu.vis_rotator->zshooter_sys.k1_rnas.zshooter.zspec.zspec_visible.rotator_hw).class: driver_conn
(zshooter_sys.k1_rnas.zshooter.zspec.zspec_control_box.zspec_ubuntu.vis_adc->zshooter_sys.k1_rnas.zshooter.zspec.zspec_visible.adc_hw).class: driver_conn
(zshooter_sys.k1_rnas.zshooter.zspec.zspec_control_box.zspec_ubuntu.vis_nodder->zshooter_sys.k1_rnas.zshooter.zspec.zspec_visible.nodder_hw).class: driver_conn
(zshooter_sys.k1_rnas.zshooter.zspec.zspec_control_box.zspec_ubuntu.vis_slit->zshooter_sys.k1_rnas.zshooter.zspec.zspec_visible.slit_hw).class: driver_conn
(zshooter_sys.k1_rnas.zshooter.zspec.zspec_control_box.zspec_ubuntu.zspec_focus_b->zshooter_sys.k1_rnas.zshooter.zspec.zspec_visible.dcs_b.focus_hw).class: driver_conn
(zshooter_sys.k1_rnas.zshooter.zspec.zspec_control_box.zspec_ubuntu.zspec_focus_g->zshooter_sys.k1_rnas.zshooter.zspec.zspec_visible.dcs_g.focus_hw).class: driver_conn
(zshooter_sys.k1_rnas.zshooter.zspec.zspec_control_box.zspec_ubuntu.zspec_focus_r->zshooter_sys.k1_rnas.zshooter.zspec.zspec_visible.dcs_r.focus_hw).class: driver_conn
(zshooter_sys.k1_rnas.zshooter.zspec.zspec_control_box.zspec_ubuntu.ir_rotator->zshooter_sys.k1_rnas.zshooter.zspec.zspec_nir.cryostat.rotator_hw).class: driver_conn
(zshooter_sys.k1_rnas.zshooter.zspec.zspec_control_box.zspec_ubuntu.ir_adc->zshooter_sys.k1_rnas.zshooter.zspec.zspec_nir.cryostat.adc_hw).class: driver_conn
(zshooter_sys.k1_rnas.zshooter.zspec.zspec_control_box.zspec_ubuntu.ir_nodder->zshooter_sys.k1_rnas.zshooter.zspec.zspec_nir.cryostat.nodder_hw).class: driver_conn
(zshooter_sys.k1_rnas.zshooter.zspec.zspec_control_box.zspec_ubuntu.ir_slit->zshooter_sys.k1_rnas.zshooter.zspec.zspec_nir.cryostat.slit_hw).class: driver_conn
(zshooter_sys.k1_rnas.zshooter.zspec.zspec_control_box.zspec_ubuntu.zfront_control->zshooter_sys.k1_rnas.zshooter.zfront.selector_controller).class: driver_conn
(zshooter_sys.k1_rnas.zshooter.zspec.zspec_control_box.zspec_ubuntu.zfront_control->zshooter_sys.k1_rnas.zshooter.zfront.zcal.cal_controller).class: driver_conn
(zshooter_sys.k1_rnas.zshooter.zspec.zspec_control_box.zspec_ubuntu.glycol_monitor->zshooter_sys.k1_rnas.zshooter.glycol_manifold).class: driver_conn
(zshooter_sys.k1_rnas.zshooter.zspec.zspec_control_box.zspec_ubuntu.temp_log->zshooter_sys.k1_rnas.zshooter.zspec.zspec_visible.temp_monitor_hub_hw).class: driver_conn
(zshooter_sys.k1_rnas.zshooter.zspec.zspec_control_box.zspec_ubuntu.temp_log->zshooter_sys.k1_rnas.zshooter.zimage.temp_monitor_hub_hw).class: driver_conn
(zshooter_sys.k1_rnas.zshooter.zspec.zspec_control_box.zspec_ubuntu.temp_log->zshooter_sys.k1_rnas.zshooter.zspec.zspec_nir.temp_controller_hw).class: driver_conn
(zshooter_sys.k1_rnas.zshooter.zspec.zspec_control_box.zspec_ubuntu.vacuum_monitor->zshooter_sys.k1_rnas.zshooter.zspec.zspec_visible.dcs_*.vacuum_gauge).class: driver_conn
(zshooter_sys.k1_rnas.zshooter.zspec.zspec_control_box.zspec_ubuntu.vacuum_monitor->zshooter_sys.k1_rnas.zshooter.zspec.zspec_nir.vacuum_gauge).class: driver_conn
(zshooter_sys.k1_rnas.zshooter.zspec.zspec_control_box.zspec_ubuntu.shutter_monitor->zshooter_sys.k1_rnas.zshooter.zspec.zspec_nir.cryostat.shutter_hw).class: driver_conn
(zshooter_sys.k1_rnas.zshooter.zspec.zspec_control_box.zspec_ubuntu.shutter_monitor->zshooter_sys.k1_rnas.zshooter.zspec.zspec_visible.shutter_hw).class: driver_conn