software_runtime.zimage_readout_pc.readout_u -> drp_runtime.drp_pc.raw_archive_writer: {
  class: publish_conn
  label: ~raw_frame
}
software_runtime.zimage_readout_pc.readout_v -> drp_runtime.drp_pc.raw_archive_writer: {
  class: publish_conn
  label: ~raw_frame
}
software_runtime.zimage_readout_pc.readout_z -> drp_runtime.drp_pc.raw_archive_writer: {
  class: publish_conn
  label: ~raw_frame
}
software_runtime.zspec_readout_pc.readout_opt_b -> drp_runtime.drp_pc.raw_archive_writer: {
  class: publish_conn
  label: ~raw_frame
}
software_runtime.zspec_readout_pc.readout_opt_g -> drp_runtime.drp_pc.raw_archive_writer: {
  class: publish_conn
  label: ~raw_frame
}
software_runtime.zspec_readout_pc.readout_opt_r -> drp_runtime.drp_pc.raw_archive_writer: {
  class: publish_conn
  label: ~raw_frame
}
software_runtime.zspec_readout_pc.readout_ir_yj -> drp_runtime.drp_pc.raw_archive_writer: {
  class: publish_conn
  label: ~raw_frame
}
software_runtime.zspec_readout_pc.readout_ir_h -> drp_runtime.drp_pc.raw_archive_writer: {
  class: publish_conn
  label: ~raw_frame
}
software_runtime.zspec_readout_pc.readout_ir_k -> drp_runtime.drp_pc.raw_archive_writer: {
  class: publish_conn
  label: ~raw_frame
}

software_runtime.zimage_readout_pc.readout_u -> software_runtime.observer_gui: {
  class: publish_conn
  label: ~raw_frame
}
software_runtime.zspec_readout_pc.readout_opt_b -> software_runtime.observer_gui: {
  class: publish_conn
  label: ~raw_frame
}

software_runtime.zimage_readout_pc.readout_u -> drp_runtime.drp_pc.prelim_reducer: {
  class: publish_conn
  label: ~raw_frame
}
software_runtime.zspec_readout_pc.readout_opt_b -> drp_runtime.drp_pc.prelim_reducer: {
  class: publish_conn
  label: ~raw_frame
}

drp_runtime.drp_pc.prelim_reducer -> software_runtime.observer_gui: {
  class: publish_conn
  label: ~prelim_products
}
software_runtime.zshooter_pc.vis_slitcam -> software_runtime.zshooter_pc.fine_guiding: {
  class: publish_conn
  label: ~slitcam_stream
}
software_runtime.zshooter_pc.ir_slitcam -> software_runtime.zshooter_pc.fine_guiding: {
  class: publish_conn
  label: ~slitcam_stream
}
