zshooter_sys.k1_server_room.zimage_readout_computer.readout_u -> zshooter_sys.k1_server_room.zshooter_reduction_computer.raw_archive_writer: {
  class: publish_conn
  label: ~raw_frame
}
zshooter_sys.k1_server_room.zimage_readout_computer.readout_v -> zshooter_sys.k1_server_room.zshooter_reduction_computer.raw_archive_writer: {
  class: publish_conn
  label: ~raw_frame
}
zshooter_sys.k1_server_room.zimage_readout_computer.readout_z -> zshooter_sys.k1_server_room.zshooter_reduction_computer.raw_archive_writer: {
  class: publish_conn
  label: ~raw_frame
}
zshooter_sys.k1_server_room.zspec_readout_computer.readout_opt_b -> zshooter_sys.k1_server_room.zshooter_reduction_computer.raw_archive_writer: {
  class: publish_conn
  label: ~raw_frame
}
zshooter_sys.k1_server_room.zspec_readout_computer.readout_opt_g -> zshooter_sys.k1_server_room.zshooter_reduction_computer.raw_archive_writer: {
  class: publish_conn
  label: ~raw_frame
}
zshooter_sys.k1_server_room.zspec_readout_computer.readout_opt_r -> zshooter_sys.k1_server_room.zshooter_reduction_computer.raw_archive_writer: {
  class: publish_conn
  label: ~raw_frame
}
zshooter_sys.k1_server_room.zspec_readout_computer.readout_ir_yj -> zshooter_sys.k1_server_room.zshooter_reduction_computer.raw_archive_writer: {
  class: publish_conn
  label: ~raw_frame
}
zshooter_sys.k1_server_room.zspec_readout_computer.readout_ir_h -> zshooter_sys.k1_server_room.zshooter_reduction_computer.raw_archive_writer: {
  class: publish_conn
  label: ~raw_frame
}
zshooter_sys.k1_server_room.zspec_readout_computer.readout_ir_k -> zshooter_sys.k1_server_room.zshooter_reduction_computer.raw_archive_writer: {
  class: publish_conn
  label: ~raw_frame
}

zshooter_sys.k1_server_room.zimage_readout_computer.readout_u -> observer_gui: {
  class: publish_conn
  label: ~raw_frame
}
zshooter_sys.k1_server_room.zspec_readout_computer.readout_opt_b -> observer_gui: {
  class: publish_conn
  label: ~raw_frame
}

zshooter_sys.k1_server_room.zimage_readout_computer.readout_u -> zshooter_sys.k1_server_room.zshooter_reduction_computer.prelim_reducer: {
  class: publish_conn
  label: ~raw_frame
}
zshooter_sys.k1_server_room.zspec_readout_computer.readout_opt_b -> zshooter_sys.k1_server_room.zshooter_reduction_computer.prelim_reducer: {
  class: publish_conn
  label: ~raw_frame
}

zshooter_sys.k1_server_room.zshooter_reduction_computer.prelim_reducer -> observer_gui: {
  class: publish_conn
  label: ~prelim_products
}
zshooter_sys.k1_rnas.zshooter.zspec.zspec_control_box.zspec_ubuntu.vis_slitcam -> zshooter_sys.k1_rnas.zshooter.zspec.zspec_control_box.zspec_ubuntu.fine_guiding: {
  class: publish_conn
  label: ~slitcam_stream
}
zshooter_sys.k1_rnas.zshooter.zspec.zspec_control_box.zspec_ubuntu.ir_slitcam -> zshooter_sys.k1_rnas.zshooter.zspec.zspec_control_box.zspec_ubuntu.fine_guiding: {
  class: publish_conn
  label: ~slitcam_stream
}
