software_runtime.observer_gui -> software_runtime.zimage_readout_pc.readout_u: {
  class: command_conn
}
software_runtime.observer_gui -> software_runtime.zimage_readout_pc.readout_v: {
  class: command_conn
}
software_runtime.observer_gui -> software_runtime.zimage_readout_pc.readout_z: {
  class: command_conn
}
software_runtime.observer_gui -> software_runtime.zspec_readout_pc.readout_opt_b: {
  class: command_conn
}
software_runtime.observer_gui -> software_runtime.zspec_readout_pc.readout_opt_g: {
  class: command_conn
}
software_runtime.observer_gui -> software_runtime.zspec_readout_pc.readout_opt_r: {
  class: command_conn
}
software_runtime.observer_gui -> software_runtime.zspec_readout_pc.readout_ir_yj: {
  class: command_conn
}
software_runtime.observer_gui -> software_runtime.zspec_readout_pc.readout_ir_h: {
  class: command_conn
}
software_runtime.observer_gui -> software_runtime.zspec_readout_pc.readout_ir_k: {
  class: command_conn
}
